{
 "title": "Метрики demo-приложения",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Временные метрики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время обработки запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "simple_get_method_execution_seconds{quantile=\"$quantile\"}",
       "legendFormat": "Время выполнения простого GET-запроса {{quantile}}"
      },
      {
       "expr": "get_method_with_param_execution_seconds{quantile=\"$quantile\"}",
       "legendFormat": "Время выполнения GET-запроса с параметрами {{quantile}}"
      },
      {
       "expr": "get_method_with_header_execution_seconds{quantile=\"$quantile\"}",
       "legendFormat": "Время выполнения GET-запроса с заголовками {{quantile}}"
      },
      {
       "expr": "simple_post_method_execution_seconds{quantile=\"$quantile\"}",
       "legendFormat": "Время выполнения POST-запроса {{quantile}}"
      }
     ]
    },
    {
     "title": "Время обработки сообщений из Kafka",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_seconds{quantile=\"$quantile\"}",
       "legendFormat": "Время обработки сообщений из топика {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Количественные метрики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество обработанных запросов в секунду",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(simple_get_method_execution_seconds_count[$__rate_interval])",
       "legendFormat": "Количество простых GET-запросов"
      },
      {
       "expr": "rate(get_method_with_param_execution_seconds_count[$__rate_interval])",
       "legendFormat": "Количество GET-запросов с параметрами"
      },
      {
       "expr": "rate(get_method_with_header_execution_seconds_count[$__rate_interval])",
       "legendFormat": "Количество GET-запросов с заголовками"
      },
      {
       "expr": "rate({\"simple_post_method_execution_seconds_count \"}[$__rate_interval])",
       "legendFormat": "Количество POST-запросов"
      }
     ]
    },
    {
     "title": "Количество обработанных запросов в секунду",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(kafka_consumer_seconds_count[$__rate_interval])",
       "legendFormat": "Количество вычитанных сообщений из топика"
      }
     ]
    }
   ]
  }
 ]
}