scrape_configs:
  - job_name: 'jmeter-demo'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['app:8081']
  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'kafka-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'jmx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['jmx-exporter:5556']